Cargo.toml
src/error.rs
src/lib.rs
src/local.rs
src/source.rs
src/spanned.rs

based on top of #24 (only the last "merge axoerror..." commit is new)
This introduces a `SourceFile` type which is basically a readonly String version of Asset wrapped in an Arc. The purpose of this type is to be cheap to clone and pass around everywhere so that errors can refer to it (using the miette `#[source_code]` and `#[label]` attributes). The Arc ensures this is cheap at minimal overhead. The String ensures the contents make sense to display.
I don't think any types should be unified here, they all make sense to exist on their own. For instance images should never be SourceFiles. That said I expect anything working with text files will probably prefer to work with SourceFile?
This also introduces a `Spanned<T>` type which tries to behave like `Box<T>` in the sense that it's "as …

Moar assets

---

src/source.rs
tests/source.rs

This makes it possible to get spans even when using a tool that doesn't support them as long as it returns actual substrings pointing into the original SourceFile's inner String.

add SourceFile::span_for_substr

---

Cargo.toml
src/compression.rs
src/error.rs
src/lib.rs
src/local.rs
tests/local_new.rs
tests/local_remove.rs

Adds:
- Parent directory creation to `LocalAsset::write_new`,
- `LocalAsset::create_directory` to create a single directory,
- `LocalAsset::remove` to remove a file/directory,
- `LocalAsset::tar_[gz,xz,zstd]_dir` to create tar archives,
- `LocalAsset::zip_dir` to create zip archives
This should replace _most_ of the existing fs code within cargo-dist, which would be the next step after merging and cutting a release.

feat: add more methods used in `cargo-dist`

---

.gitignore
src/local.rs
src/source.rs
tests/local_new.rs
tests/local_remove.rs
tests/local_write.rs

Changes the signature of those two functions to not explicitly take a `filename` and a `dest_dir` argument, instead now taking a `dest_path` argument, from which we infer everything else.
These two functions aren't currently in use in axo code (outside of https://github.com/axodotdev/cargo-dist/pull/229), so changing the signatures should be fine, at least for our use, as long as we mark the change as breaking correspondingly.

feat: refactor local function to use AsRef, simplify write arguments

---

.gitignore
Cargo.toml
src/compression.rs
src/lib.rs
src/local.rs

This PR hides compression features behind a feature flag (`compression`), which itself can be broken up into more granular features (`compression-tar` and `compression-zip`).

feat: separate compression into cargo features

---

.github/workflows/oranda.yml

The following updates are performed:
* update [`actions/checkout`](https://github.com/actions/checkout) to v3
* replace [unmaintained](https://github.com/actions-rs/toolchain/issues/216) `actions-rs/toolchain` by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain)
Still using the outdated / unmaintained actions will generate several warnings in CI runs, for example in https://github.com/axodotdev/axoasset/actions/runs/4951115139:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions-rs/toolchain@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
The PR will get rid of those warnings.

update GitHub Actions CI

---

src/compression.rs
src/dirs.rs
src/error.rs
src/lib.rs
src/local.rs
src/remote.rs
tests/local_copy.rs

* copy_named allows you to specify a name for the dest file
* copy_dir is like copy but for dirs
* copy_dir_named is both put together
These APIs are desired for cargo-dist

feat(copy): add more copying APIs to LocalAsset

---

oranda.json

The syntax has changed since the last time this was changed.
Should fix this error on the most recent push: https://github.com/axodotdev/axoasset/actions/runs/5801175747/job/15724847546

fix: oranda.json

---

Cargo.toml

We only use MIME type-based detection; we never decode or encode images. Removing the default features from the images crate reduces its dependency tree substantially, cutting out a number of things we never actually use.
I checked, and this eliminates 29 dependencies that are never used by this crate or our projects that use it.

chore(deps): remove image decoders

---

Cargo.toml

This ensures that liblzma won't be dynamically linked against.

feat: use xz2 static feature

---

Cargo.toml
src/compression.rs

this is an error that dates back to the first commits of cargo-dist -- seeing zlib and mentally replacing it with zstd

fix: actually compress zstd with zstd

---

CHANGELOG.md
Cargo.toml

We need to get miette 7.0.0 in all our crates to be able to upgrade downstream projects like cargo-dist, so I decided to cut a new release here.

release: 0.7.0

---

src/compression.rs
src/error.rs
src/local.rs

Although axoasset's had support for *creating* archives for awhile, it hasn't supported *extracting* them yet. This starts that off with a few options: methods that extract the entire tarball/zip to a directory, and methods that extract a single file and return the raw bytes.

feat: add zip/tarball decompression

---

src/source.rs
tests/source.rs

While many JSON parsers can read UTF-8 data that begins with a byte order mark, json-serde can't. This caused an error for us when reading data that originated from PowerShell on Windows, which always writes a byte order mark at the beginning of the file even when using UTF-8.
I've added a test for this and confirmed the new test fails without the new changes.
See: https://github.com/serde-rs/json/issues/1115

fix: parse JSON with UTF-8 BOMs

---

Cargo.toml
tests/local_write.rs

Historically this has had one of our heavier dependency trees, though it's currently down to about 6 crates and ~30-40KB in the final binary. That's still not nothing, and since it's only used in the `remote` feature, we can easily scope it to only be used there.

chore: make image optional, use in remote

---

Cargo.toml

This makes it easier for apps using more than one library that uses reqwest to ensure all are using the same version.

chore: relax reqwest version range

---

src/remote.rs

Previously we'd error out if we couldn't decide on a filename for the file. Now, if we don't assign an extension based on the mimetype, we'll simply return the original filename unmodified.
cf these custom versions of `RemoteAsset::copy` - we'll want to make sure this does what we want before merging. https://github.com/axodotdev/cargo-dist/blob/66b5ffaaee88a375c69f1c655ac26b0261cb20f3/cargo-dist/src/sign/ssldotcom.rs#L203

fix: better handle extensions for unrecognized mimetypes

---

src/local.rs

Because this writes a `.zip` file, not a `.tar` file.

chore: fix typo in `LocalAsset::zip_dir`

---

src/lib.rs
src/remote.rs

This was placed in the `remote` module, which isn't actually exposed to external users. It needs to be `pub use`d from `lib` if it's going to be accessible.

fix: move pub use reqwest

---

Cargo.toml

This was bumped in 9d02db2624c5344e6176b5e8960e6eeb4522410e, before we started being careful with the version changes in Cargo.toml.

fix: relax serde_json

---

Cargo.lock
Cargo.toml
src/compression.rs

This introduces three environment variables, with the following defaults:
* `AXOASSET_GZ_LEVEL=6`
* `AXOASSET_XZ_LEVEL=9`
* `AXOASSET_ZSTD_LEVEL=3`
(The defaults are unchanged, but when we iterate on dist builds using dist itself, exporting `AXOASSET_XZ_LEVEL=1` will make it go faster — it is _genuinely_ the blocker on warm builds lol)

Allow overriding compression levels with environment variables

---

src/compression.rs

We weren't setting the `unix_permissions` parameter on the options object to ensure that the compressed files get the same permissions as the source files.
Fixes axodotdev/cargo-dist#3032.
cc @jackTabsCode

fix: preserve Unix permissions in ZIPs
